import os
import platform
import sys
from utils import get_version, get_resource_path, get_version_info


class TranslationDict(str):
    def __new__(cls, translations):
        # Import here to avoid circular import
        from utils import get_locale

        language = get_locale()
        # Create the string instance with the current language translation
        current_text = translations.get(language, translations.get("en_US", ""))
        instance = str.__new__(cls, current_text)
        instance._translations = translations
        return instance

    def __missing__(self, key):
        return self._translations.get("en_US", "")

    def __str__(self):
        from utils import get_locale

        language = get_locale()
        return self._translations.get(language, self._translations.get("en_US", ""))

    def __repr__(self):
        from utils import get_locale

        language = get_locale()
        return self._translations.get(language, self._translations.get("en_US", ""))

    def format(self, *args, **kwargs):
        from utils import get_locale

        language = get_locale()
        return self._translations.get(
            language, self._translations.get("en_US", "")
        ).format(*args, **kwargs)

    def get(self, key, default=""):
        return self._translations.get(key, default)


LANGUAGES = {
    "English": "en_US",
    "Español": "es_ES",
    "Deutsch": "de_DE",
    "Français": "fr_FR",
    "Italiano": "it_IT",
    "Polski": "pl_PL",
    "Português": "pt_PT",
    "Türkçe": "tr_TR",
    "Tiếng Việt": "vi_VN",
    "Bahasa Indonesia": "id_ID",
    "Bahasa Melayu": "ms_MY",
    "ไทย": "th_TH",
    "Українська": "uk_UA",
    "Русский": "ru_RU",
    "中国人": "zh_CN",
    "日本語": "ja_JP",
    "한국어": "ko_KR",
    "हिन्दी": "hi_IN",
    "বাংলা": "bn_BD",
    "اردو": "ur_PK",
    "العربية": "ar_SA",
    "فارسی": "fa_IR",
}

# Program Information
PROGRAM_NAME = "AutoSubSync"

PROGRAM_TAGLINE = {
    "en_US": "Subtitle Synchronizer",
    "es_ES": "Sincronizador de Subtítulos",
    "tr_TR": "Altyazı Senkronizatörü",
    "zh_CN": "字幕同步器",
    "ru_RU": "Синхронизатор Субтитров",
    "pl_PL": "Synchronizator Napisów",
    "uk_UA": "Синхронізатор Субтитрів",
    "ja_JP": "字幕シンクロナイザー",
    "ko_KR": "자막 동기화 도구",
    "hi_IN": "उपशीर्षक सिंक्रोनाइज़र",
    "bn_BD": "সাবটাইটেল সিঙ্ক্রোনাইজার",
    "it_IT": "Sincronizzatore di Sottotitoli",
    "fr_FR": "Synchroniseur de Sous-titres",
    "de_DE": "Untertitel-Synchronisierer",
    "pt_PT": "Sincronizador de Legendas",
    "ar_SA": "مزامن الترجمات",
    "vi_VN": "Bộ Đồng Bộ Phụ Đề",
    "fa_IR": "همگام‌ساز زیرنویس",
    "id_ID": "Sinkronisasi Subtitle",
    "ms_MY": "Penyegerak Sarikata",
    "th_TH": "ตัวซิงค์คำบรรยาย",
    "ur_PK": "سب ٹائٹل سنکرونائزر",
}

PROGRAM_DESCRIPTION = {
    "en_US": "AutoSubSync is a user-friendly Python tool that helps you easily synchronize subtitle files. It supports various subtitle formats and allows you to sync subtitles effortlessly by shifting subtitle timings automatically or manually with a millisecond offset.",
    "es_ES": "AutoSubSync es una herramienta de Python fácil de usar que te ayuda a sincronizar archivos de subtítulos fácilmente. Compatible con varios formatos de subtítulos y permite sincronizar subtítulos sin esfuerzo ajustando los tiempos automática o manualmente con un desplazamiento en milisegundos.",
    "tr_TR": "AutoSubSync, altyazı dosyalarını kolayca senkronize etmenize yardımcı olan kullanıcı dostu bir Python aracıdır. Çeşitli altyazı formatlarını destekler ve altyazı zamanlamalarını otomatik veya manuel olarak milisaniye kayması ile değiştirerek altyazıları zahmetsizce senkronize etmenizi sağlar.",
    "zh_CN": "AutoSubSync 是一个用户友好的 Python 工具，帮助您轻松同步字幕文件。它支持各种字幕格式，允许您通过自动或手动调整字幕时间偏移（以毫秒为单位）来轻松同步字幕。",
    "ru_RU": "AutoSubSync - это удобный инструмент Python, который помогает легко синхронизировать файлы субтитров. Поддерживает различные форматы субтитров и позволяет синхронизировать субтитры без усилий, сдвигая время субтитров автоматически или вручную со смещением в миллисекундах.",
    "pl_PL": "AutoSubSync to przyjazne użytkownikowi narzędzie Python, które pomaga łatwo synchronizować pliki napisów. Obsługuje różne formaty napisów i pozwala synchronizować napisy bez wysiłku poprzez przesuwanie czasów napisów automatycznie lub ręcznie z przesunięciem w milisekundach.",
    "uk_UA": "AutoSubSync - це зручний інструмент Python, який допомагає легко синхронізувати файли субтитрів. Підтримує різні формати субтитрів і дозволяє синхронізувати субтитри без зусиль, зміщуючи час субтитрів автоматично або вручну з зміщенням у мілісекундах.",
    "ja_JP": "AutoSubSyncは字幕ファイルを簡単に同期するのに役立つユーザーフレンドリーなPythonツールです。様々な字幕フォーマットをサポートし、字幕のタイミングを自動的または手動でミリ秒オフセットでシフトすることで、字幕を簡単に同期できます。",
    "ko_KR": "AutoSubSync는 자막 파일을 쉽게 동기화하는 데 도움이 되는 사용자 친화적인 Python 도구입니다. 다양한 자막 형식을 지원하며 자막 타이밍을 자동 또는 수동으로 밀리초 오프셋으로 이동하여 자막을 쉽게 동기화할 수 있습니다.",
    "hi_IN": "AutoSubSync एक उपयोगकर्ता-अनुकूल Python उपकरण है जो आपको उपशीर्षक फाइलों को आसानी से सिंक्रोनाइज़ करने में मदद करता है। यह विभिन्न उपशीर्षक प्रारूपों का समर्थन करता है और उपशीर्षक समय को स्वचालित या मैन्युअल रूप से मिलीसेकंड ऑफसेट के साथ स्थानांतरित करके उपशीर्षक को आसानी से सिंक्रोनाइज़ करने की अनुमति देता है।",
    "bn_BD": "AutoSubSync একটি ব্যবহারকারী-বান্ধব Python টুল যা আপনাকে সাবটাইটেল ফাইলগুলি সহজে সিঙ্ক্রোনাইজ করতে সাহায্য করে। এটি বিভিন্ন সাবটাইটেল ফরম্যাট সমর্থন করে এবং সাবটাইটেল টাইমিং স্বয়ংক্রিয় বা ম্যানুয়ালভাবে মিলিসেকেন্ড অফসেট দিয়ে স্থানান্তর করে সাবটাইটেল সহজে সিঙ্ক্রোনাইজ করতে দেয়।",
    "it_IT": "AutoSubSync è uno strumento Python user-friendly che ti aiuta a sincronizzare facilmente i file dei sottotitoli. Supporta vari formati di sottotitoli e ti permette di sincronizzare i sottotitoli senza sforzo spostando i timing automaticamente o manualmente con un offset in millisecondi.",
    "fr_FR": "AutoSubSync est un outil Python convivial qui vous aide à synchroniser facilement les fichiers de sous-titres. Il prend en charge divers formats de sous-titres et vous permet de synchroniser les sous-titres sans effort en décalant les timings automatiquement ou manuellement avec un décalage en millisecondes.",
    "de_DE": "AutoSubSync ist ein benutzerfreundliches Python-Tool, das Ihnen hilft, Untertiteldateien einfach zu synchronisieren. Es unterstützt verschiedene Untertitelformate und ermöglicht es, Untertitel mühelos zu synchronisieren, indem die Untertitel-Timings automatisch oder manuell mit einem Millisekunden-Offset verschoben werden.",
    "pt_PT": "AutoSubSync é uma ferramenta Python amigável que ajuda a sincronizar facilmente ficheiros de legendas. Suporta vários formatos de legendas e permite sincronizar legendas sem esforço, deslocando os tempos das legendas automaticamente ou manualmente com um deslocamento em milissegundos.",
    "ar_SA": "AutoSubSync هو أداة Python سهلة الاستخدام تساعدك على مزامنة ملفات الترجمات بسهولة. يدعم صيغ ترجمات مختلفة ويسمح لك بمزامنة الترجمات بسهولة عن طريق تحريك أوقات الترجمات تلقائيًا أو يدويًا بإزاحة بالميلي ثانية.",
    "vi_VN": "AutoSubSync là một công cụ Python thân thiện với người dùng giúp bạn dễ dàng đồng bộ hóa các tệp phụ đề. Nó hỗ trợ nhiều định dạng phụ đề khác nhau và cho phép bạn đồng bộ phụ đề một cách dễ dàng bằng cách dịch chuyển thời gian phụ đề tự động hoặc thủ công với độ lệch mili giây.",
    "fa_IR": "AutoSubSync ابزاری کاربر پسند Python است که به شما کمک می‌کند فایل‌های زیرنویس را به راحتی همگام‌سازی کنید. از فرمت‌های مختلف زیرنویس پشتیبانی می‌کند و به شما اجازه می‌دهد زیرنویس‌ها را با جابجا کردن زمان‌بندی زیرنویس به صورت خودکار یا دستی با افست میلی‌ثانیه، بدون زحمت همگام‌سازی کنید.",
    "id_ID": "AutoSubSync adalah alat Python yang ramah pengguna yang membantu Anda dengan mudah menyinkronkan file subtitle. Mendukung berbagai format subtitle dan memungkinkan Anda menyinkronkan subtitle dengan mudah dengan menggeser waktu subtitle secara otomatis atau manual dengan offset milidetik.",
    "ms_MY": "AutoSubSync adalah alat Python yang mesra pengguna yang membantu anda menyegerakkan fail sarikata dengan mudah. Ia menyokong pelbagai format sarikata dan membolehkan anda menyegerakkan sarikata dengan mudah dengan mengalihkan masa sarikata secara automatik atau manual dengan offset milisaat.",
    "th_TH": "AutoSubSync เป็นเครื่องมือ Python ที่ใช้งานง่ายที่ช่วยให้คุณซิงค์ไฟล์คำบรรยายได้อย่างง่ายดาย รองรับรูปแบบคำบรรยายต่างๆ และช่วยให้คุณซิงค์คำบรรยายได้อย่างง่ายดายโดยการปรับเวลาคำบรรยายโดยอัตโนมัติหรือด้วยตนเองด้วยการชดเชยมิลลิวินาที",
    "ur_PK": "AutoSubSync ایک صارف دوست Python ٹول ہے جو آپ کو سب ٹائٹل فائلوں کو آسانی سے سنکرونائز کرنے میں مدد کرتا ہے۔ یہ مختلف سب ٹائٹل فارمیٹس کو سپورٹ کرتا ہے اور سب ٹائٹل ٹائمنگ کو خودکار یا دستی طور پر ملی سیکنڈ آفسیٹ کے ساتھ منتقل کرکے سب ٹائٹلز کو آسانی سے سنکرونائز کرنے کی اجازت دیتا ہے۔",
}

GITHUB_URL = "https://github.com/denizsafak/AutoSubSync"
GITHUB_VERSION_URL = "https://raw.githubusercontent.com/denizsafak/AutoSubSync/refs/heads/main/main/VERSION"
GITHUB_LATEST_RELEASE_URL = "https://github.com/denizsafak/AutoSubSync/releases/latest"
VERSION = get_version()

DEFAULT_OPTIONS = {
    "language": "en_US",  # Will be set properly after LANGUAGES is defined
    "sync_tool": "ffsubsync",
    "automatic_save_location": "save_next_to_input_subtitle",
    "manual_save_location": "save_next_to_input_subtitle",
    "remember_changes": True,
    "check_updates_startup": True,
    "batch_mode": False,
    "add_tool_prefix": False,
    "backup_subtitles_before_overwriting": True,
    "keep_extracted_subtitles": False,
    "keep_converted_subtitles": False,
    "output_subtitle_encoding": "same_as_input",
    "add_ms_prefix_to_filename": True,
    "keep_log_records": True,
    "theme": "system",
    "skip_previously_processed_videos": True,
    "auto_rename_bracket_paths": False,
}

# ffmpeg and ffprobe paths
_exe_suffix = ".exe" if platform.system() == "Windows" else ""
_ffmpeg_res = get_resource_path("resources.ffmpeg-bin", f"ffmpeg{_exe_suffix}")
_ffprobe_res = get_resource_path("resources.ffmpeg-bin", f"ffprobe{_exe_suffix}")

# Check if bundled executables exist
if (
    _ffmpeg_res
    and _ffprobe_res
    and os.path.isfile(_ffmpeg_res)
    and os.path.isfile(_ffprobe_res)
):
    FFMPEG_EXECUTABLE = os.path.normpath(_ffmpeg_res)
    FFPROBE_EXECUTABLE = os.path.normpath(_ffprobe_res)
    FFMPEG_DIR = os.path.dirname(FFMPEG_EXECUTABLE)
else:
    # For pip installs (not in frozen builds), defer static_ffmpeg initialization
    # until after GUI loads to show download progress
    FFMPEG_EXECUTABLE = "ffmpeg"
    FFPROBE_EXECUTABLE = "ffprobe"
    FFMPEG_DIR = None

# Flag to indicate if static_ffmpeg needs to be initialized
NEEDS_STATIC_FFMPEG = (
    not getattr(sys, "frozen", False)
    and not (
        _ffmpeg_res
        and _ffprobe_res
        and os.path.isfile(_ffmpeg_res)
        and os.path.isfile(_ffprobe_res)
    )
)

# Synchronization tools
SYNC_TOOLS = {
    "ffsubsync": {
        "version": get_version_info("ffsubsync"),
        "description": {
            "en_US": "Automagically synchronize subtitles with video",
            "es_ES": "Sincroniza automáticamente los subtítulos con el video",
            "tr_TR": "Altyazıları videoyla otomatik olarak senkronize edin",
            "zh_CN": "自动将字幕与视频同步",
            "ru_RU": "Автоматически синхронизируйте субтитры с видео",
            "pl_PL": "Automatycznie synchronizuj napisy z wideo",
            "uk_UA": "Автоматично синхронізуйте субтитри з відео",
            "ja_JP": "字幕を動画と自動的に同期します",
            "ko_KR": "자막을 비디오와 자동으로 동기화합니다",
            "hi_IN": "स्वचालित रूप से उपशीर्षकों को वीडियो के साथ सिंक्रनाइज़ करें",
            "bn_BD": "স্বয়ংক্রিয়ভাবে সাবটাইটেল ভিডিওর সাথে সিঙ্ক করুন",
            "it_IT": "Sincronizza automaticamente i sottotitoli con il video",
            "fr_FR": "Synchronisez automatiquement les sous-titres avec la vidéo",
            "de_DE": "Synchronisieren Sie Untertitel automatisch mit dem Video",
            "pt_PT": "Sincronize automaticamente as legendas com o vídeo",
            "ar_SA": "قم بمزامنة الترجمات مع الفيديو تلقائيًا",
            "vi_VN": "Tự động đồng bộ phụ đề với video",
            "fa_IR": "زیرنویس‌ها را به طور خودکار با ویدیو همگام‌سازی کنید",
            "id_ID": "Sinkronkan subtitle dengan video secara otomatis",
            "ms_MY": "Segerakkan sarikata dengan video secara automatik",
            "th_TH": "ซิงค์คำบรรยายกับวิดีโอโดยอัตโนมัติ",
            "ur_PK": "سب ٹائٹلز کو ویڈیو کے ساتھ خودکار طور پر سنکرونائز کریں",
        },
        "github": "https://github.com/smacke/ffsubsync",
        "documentation": "https://ffsubsync.readthedocs.io/",
        "supported_formats": [".srt", ".ass", ".ssa", ".vtt"],
        "supports_subtitle_as_reference": True,
        "type": "module",
        "module": "call_ffsubsync",
        "cmd_structure": ["{reference}", "-i", "{subtitle}", "-o", "{output}"],
        "options": {
            "dont_fix_framerate": {
                "type": "checkbox",
                "label": {
                    "en_US": "Don't fix framerate",
                    "es_ES": "No corregir velocidad de fotogramas",
                    "tr_TR": "Kare hızını düzeltme",
                    "zh_CN": "不修复帧率",
                    "ru_RU": "Не исправлять частоту кадров",
                    "pl_PL": "Nie naprawiaj klatek na sekundę",
                    "uk_UA": "Не виправляти частоту кадрів",
                    "ja_JP": "フレームレートを修正しない",
                    "ko_KR": "프레임레이트 수정하지 않음",
                    "hi_IN": "फ्रेमरेट को ठीक न करें",
                    "bn_BD": "ফ্রেমরেট ঠিক করবেন না",
                    "it_IT": "Non correggere il framerate",
                    "fr_FR": "Ne pas corriger la fréquence d'images",
                    "de_DE": "Bildrate nicht korrigieren",
                    "pt_PT": "Não corrigir taxa de quadros",
                    "ar_SA": "لا تصحح معدل الإطارات",
                    "vi_VN": "Không sửa tốc độ khung hình",
                    "fa_IR": "نرخ فریم را اصلاح نکنید",
                    "id_ID": "Jangan perbaiki framerate",
                    "ms_MY": "Jangan betulkan kadar bingkai",
                    "th_TH": "ไม่ต้องแก้ไขอัตราเฟรม",
                    "ur_PK": "فریم ریٹ کو ٹھیک نہ کریں",
                },
                "tooltip": {
                    "en_US": "If specified, ffsubsync will not attempt to correct a framerate mismatch between reference and subtitles.\nThis can be useful when you know that the video and subtitle framerates are same, only the subtitles are out of sync.",
                    "es_ES": "Si se especifica, ffsubsync no intentará corregir una discrepancia de velocidad de fotogramas entre la referencia y los subtítulos.\nEsto puede ser útil cuando sabes que las velocidades de fotogramas del video y los subtítulos son iguales, solo los subtítulos están desincronizados.",
                    "tr_TR": "Belirtilirse, ffsubsync referans ve altyazılar arasındaki kare hızı uyumsuzluğunu düzeltmeye çalışmayacaktır.\nBu, video ve altyazı kare hızlarının aynı olduğunu bildiğinizde, sadece altyazıların senkronizasyon dışında olduğu durumlarda yararlı olabilir.",
                    "zh_CN": "如果指定，ffsubsync将不会尝试纠正参考和字幕之间的帧率不匹配。\n当您知道视频和字幕帧率相同，只是字幕不同步时，这可能很有用。",
                    "ru_RU": "Если указано, ffsubsync не будет пытаться исправить несоответствие частоты кадров между эталоном и субтитрами.\nЭто может быть полезно, когда вы знаете, что частота кадров видео и субтитров одинакова, только субтитры не синхронизированы.",
                    "pl_PL": "Jeśli określono, ffsubsync nie będzie próbował poprawić niezgodności klatek na sekundę między referencją a napisami.\nMoże to być przydatne, gdy wiesz, że klatki na sekundę wideo i napisów są takie same, tylko napisy są poza synchronizacją.",
                    "uk_UA": "Якщо вказано, ffsubsync не спробує виправити невідповідність частоти кадрів між еталоном та субтитрами.\nЦе може бути корисно, коли ви знаєте, що частота кадрів відео та субтитрів однакова, лише субтитри не синхронізовані.",
                    "ja_JP": "指定した場合、ffsubsyncは参照と字幕間のフレームレートの不一致を修正しようとしません。\nビデオと字幕のフレームレートが同じで、字幕のみが同期していないことがわかっている場合に役立ちます。",
                    "ko_KR": "지정하면 ffsubsync는 참조와 자막 간의 프레임레이트 불일치를 수정하려고 시도하지 않습니다.\n비디오와 자막 프레임레이트가 동일하고 자막만 동기화되지 않았다는 것을 알고 있을 때 유용할 수 있습니다.",
                    "hi_IN": "यदि निर्दिष्ट किया गया है, तो ffsubsync संदर्भ और उपशीर्षक के बीच फ्रेमरेट बेमेल को ठीक करने का प्रयास नहीं करेगा।\nयह तब उपयोगी हो सकता है जब आप जानते हैं कि वीडियो और उपशीर्षक फ्रेमरेट समान हैं, केवल उपशीर्षक सिंक से बाहर हैं।",
                    "bn_BD": "যদি নির্দিষ্ট করা হয়, ffsubsync রেফারেন্স এবং সাবটাইটেলের মধ্যে ফ্রেমরেট অমিল সংশোধন করার চেষ্টা করবে না।\nএটি কার্যকর হতে পারে যখন আপনি জানেন যে ভিডিও এবং সাবটাইটেল ফ্রেমরেট একই, শুধুমাত্র সাবটাইটেল সিঙ্কের বাইরে।",
                    "it_IT": "Se specificato, ffsubsync non tenterà di correggere una discrepanza di framerate tra riferimento e sottotitoli.\nQuesto può essere utile quando sai che i framerate del video e dei sottotitoli sono uguali, solo i sottotitoli sono fuori sincrono.",
                    "fr_FR": "Si spécifié, ffsubsync ne tentera pas de corriger une discordance de fréquence d'images entre la référence et les sous-titres.\nCela peut être utile lorsque vous savez que les fréquences d'images de la vidéo et des sous-titres sont identiques, seuls les sous-titres sont désynchronisés.",
                    "de_DE": "Falls angegeben, wird ffsubsync nicht versuchen, eine Bildrate-Diskrepanz zwischen Referenz und Untertiteln zu korrigieren.\nDies kann nützlich sein, wenn Sie wissen, dass die Video- und Untertitel-Bildraten gleich sind, nur die Untertitel nicht synchron sind.",
                    "pt_PT": "Se especificado, o ffsubsync não tentará corrigir uma incompatibilidade de taxa de quadros entre referência e legendas.\nIsto pode ser útil quando sabe que as taxas de quadros do vídeo e das legendas são iguais, apenas as legendas estão fora de sincronia.",
                    "ar_SA": "إذا تم تحديده، فلن يحاول ffsubsync تصحيح عدم تطابق معدل الإطارات بين المرجع والترجمات.\nيمكن أن يكون هذا مفيدًا عندما تعلم أن معدلات إطارات الفيديو والترجمات متماثلة، فقط الترجمات غير متزامنة.",
                    "vi_VN": "Nếu được chỉ định, ffsubsync sẽ không cố gắng sửa chữa sự không khớp tốc độ khung hình giữa tham chiếu và phụ đề.\nĐiều này có thể hữu ích khi bạn biết rằng tốc độ khung hình video và phụ đề giống nhau, chỉ có phụ đề bị lệch đồng bộ.",
                    "fa_IR": "اگر مشخص شود، ffsubsync تلاش نخواهد کرد تا عدم تطبیق نرخ فریم بین مرجع و زیرنویس را اصلاح کند.\nاین می‌تواند مفید باشد وقتی می‌دانید که نرخ فریم ویدیو و زیرنویس یکسان است، فقط زیرنویس‌ها همگام نیستند.",
                    "id_ID": "Jika ditentukan, ffsubsync tidak akan mencoba memperbaiki ketidakcocokan framerate antara referensi dan subtitle.\nIni bisa berguna ketika Anda tahu bahwa framerate video dan subtitle sama, hanya subtitle yang tidak sinkron.",
                    "ms_MY": "Jika dinyatakan, ffsubsync tidak akan cuba membetulkan ketidakpadanan kadar bingkai antara rujukan dan sarikata.\nIni boleh berguna apabila anda tahu bahawa kadar bingkai video dan sarikata adalah sama, hanya sarikata yang tidak segerak.",
                    "th_TH": "หากระบุ ffsubsync จะไม่พยายามแก้ไขความไม่ตรงกันของอัตราเฟรมระหว่างอ้างอิงและคำบรรยาย\nสิ่งนี้อาจมีประโยชน์เมื่อคุณรู้ว่าอัตราเฟรมของวิดีโอและคำบรรยายเหมือนกัน เพียงแค่คำบรรยายไม่ตรงกัน",
                    "ur_PK": "اگر مخصوص کیا جائے تو، ffsubsync ریفرنس اور سب ٹائٹلز کے درمیان فریم ریٹ کی عدم مطابقت کو ٹھیک کرنے کی کوشش نہیں کرے گا۔\nیہ اس وقت مفید ہو سکتا ہے جب آپ جانتے ہیں کہ ویڈیو اور سب ٹائٹل فریم ریٹ یکساں ہیں، صرف سب ٹائٹلز سنک سے باہر ہیں۔",
                },
                "argument": "--no-fix-framerate",
                "default": False,
            },
            "use_golden_section": {
                "type": "checkbox",
                "label": {
                    "en_US": "Use golden section search",
                    "es_ES": "Usar búsqueda de sección áurea",
                    "tr_TR": "Altın oran araması kullan",
                    "zh_CN": "使用黄金分割搜索",
                    "ru_RU": "Использовать поиск золотого сечения",
                    "pl_PL": "Użyj wyszukiwania złotego podziału",
                    "uk_UA": "Використовувати пошук золотого перерізу",
                    "ja_JP": "黄金分割探索を使用",
                    "ko_KR": "황금비 검색 사용",
                    "hi_IN": "स्वर्ण अनुभाग खोज का उपयोग करें",
                    "bn_BD": "গোল্ডেন সেকশন অনুসন্ধান ব্যবহার করুন",
                    "it_IT": "Usa ricerca sezione aurea",
                    "fr_FR": "Utiliser la recherche par section dorée",
                    "de_DE": "Goldenen Schnitt-Suche verwenden",
                    "pt_PT": "Usar pesquisa de secção dourada",
                    "ar_SA": "استخدم البحث بالقسم الذهبي",
                    "vi_VN": "Sử dụng tìm kiếm tỷ lệ vàng",
                    "fa_IR": "از جستجوی نسبت طلایی استفاده کنید",
                    "id_ID": "Gunakan pencarian bagian emas",
                    "ms_MY": "Gunakan carian bahagian emas",
                    "th_TH": "ใช้การค้นหาส่วนทอง",
                    "ur_PK": "گولڈن سیکشن سرچ استعمال کریں",
                },
                "tooltip": {
                    "en_US": "Use golden-section search to find the optimal ratio between video and subtitle framerates (by default, only a few common ratios are evaluated)",
                    "es_ES": "Usar búsqueda de sección áurea para encontrar la relación óptima entre las velocidades de fotogramas del video y los subtítulos (por defecto, solo se evalúan unas pocas relaciones comunes)",
                    "tr_TR": "Video ve altyazı kare hızları arasındaki optimal oranı bulmak için altın oran araması kullanın (varsayılan olarak, sadece birkaç yaygın oran değerlendirilir)",
                    "zh_CN": "使用黄金分割搜索来找到视频和字幕帧率之间的最佳比率（默认情况下，只评估几个常见比率）",
                    "ru_RU": "Использовать поиск золотого сечения для нахождения оптимального соотношения между частотой кадров видео и субтитров (по умолчанию оценивается только несколько общих соотношений)",
                    "pl_PL": "Użyj wyszukiwania złotego podziału, aby znaleźć optymalny stosunek między klatkami na sekundę wideo i napisów (domyślnie oceniane są tylko kilka powszechnych stosunków)",
                    "uk_UA": "Використовувати пошук золотого перерізу для знаходження оптимального співвідношення між частотою кадрів відео та субтитрів (за замовчуванням оцінюється лише кілька загальних співвідношень)",
                    "ja_JP": "ビデオと字幕のフレームレート間の最適な比率を見つけるために黄金分割探索を使用します（デフォルトでは、いくつかの一般的な比率のみが評価されます）",
                    "ko_KR": "비디오와 자막 프레임레이트 간의 최적 비율을 찾기 위해 황금비 검색을 사용합니다（기본적으로 몇 가지 일반적인 비율만 평가됩니다）",
                    "hi_IN": "वीडियो और उपशीर्षक फ्रेमरेट के बीच इष्टतम अनुपात खोजने के लिए स्वर्ण-अनुभाग खोज का उपयोग करें (डिफ़ॉल्ट रूप से, केवल कुछ सामान्य अनुपातों का मूल्यांकन किया जाता है)",
                    "bn_BD": "ভিডিও এবং সাবটাইটেল ফ্রেমরেটের মধ্যে সর্বোত্তম অনুপাত খুঁজে পেতে গোল্ডেন-সেকশন অনুসন্ধান ব্যবহার করুন (ডিফল্টভাবে, শুধুমাত্র কয়েকটি সাধারণ অনুপাত মূল্যায়ন করা হয়)",
                    "it_IT": "Usa la ricerca della sezione aurea per trovare il rapporto ottimale tra i framerate del video e dei sottotitoli (per impostazione predefinita, vengono valutati solo alcuni rapporti comuni)",
                    "fr_FR": "Utiliser la recherche par section dorée pour trouver le rapport optimal entre les fréquences d'images de la vidéo et des sous-titres (par défaut, seuls quelques rapports courants sont évalués)",
                    "de_DE": "Verwenden Sie die Goldenen-Schnitt-Suche, um das optimale Verhältnis zwischen Video- und Untertitel-Bildraten zu finden (standardmäßig werden nur wenige häufige Verhältnisse bewertet)",
                    "pt_PT": "Use a pesquisa de secção dourada para encontrar a proporção ideal entre as taxas de quadros do vídeo e das legendas (por padrão, apenas algumas proporções comuns são avaliadas)",
                    "ar_SA": "استخدم البحث بالقسم الذهبي للعثور على النسبة المثلى بين معدلات إطارات الفيديو والترجمات (افتراضيًا، يتم تقييم بعض النسب الشائعة فقط)",
                    "vi_VN": "Sử dụng tìm kiếm tỷ lệ vàng để tìm tỷ lệ tối ưu giữa tốc độ khung hình video và phụ đề (theo mặc định, chỉ một vài tỷ lệ phổ biến được đánh giá)",
                    "fa_IR": "از جستجوی نسبت طلایی برای یافتن نسبت بهینه بین نرخ فریم ویدیو و زیرنویس استفاده کنید (به طور پیش‌فرض، فقط چند نسبت رایج ارزیابی می‌شود)",
                    "id_ID": "Gunakan pencarian bagian emas untuk menemukan rasio optimal antara framerate video dan subtitle (secara default, hanya beberapa rasio umum yang dievaluasi)",
                    "ms_MY": "Gunakan carian bahagian emas untuk mencari nisbah optimum antara kadar bingkai video dan sarikata (secara lalai, hanya beberapa nisbah biasa yang dinilai)",
                    "th_TH": "ใช้การค้นหาส่วนทองเพื่อหาอัตราส่วนที่เหมาะสมที่สุดระหว่างอัตราเฟรมของวิดีโอและคำบรรยาย (โดยค่าเริ่มต้น จะประเมินเพียงอัตราส่วนทั่วไปไม่กี่อัน)",
                    "ur_PK": "ویڈیو اور سب ٹائٹل فریم ریٹس کے درمیان بہترین تناسب تلاش کرنے کے لیے گولڈن سیکشن سرچ استعمال کریں (ڈیفالٹ کے ذریعے، صرف کچھ عام تناسب کا جائزہ لیا جاتا ہے)",
                },
                "argument": "--gss",
                "default": False,
            },
            "vad": {
                "type": "dropdown",
                "label": {
                    "en_US": "Voice activity detector",
                    "es_ES": "Detector de actividad de voz",
                    "tr_TR": "Ses aktivite dedektörü",
                    "zh_CN": "语音活动检测器",
                    "ru_RU": "Детектор голосовой активности",
                    "pl_PL": "Detektor aktywności głosu",
                    "uk_UA": "Детектор голосової активності",
                    "ja_JP": "音声活動検出器",
                    "ko_KR": "음성 활동 감지기",
                    "hi_IN": "आवाज गतिविधि डिटेक्टर",
                    "bn_BD": "ভয়েস অ্যাক্টিভিটি ডিটেক্টর",
                    "it_IT": "Rilevatore di attività vocale",
                    "fr_FR": "Détecteur d'activité vocale",
                    "de_DE": "Sprachaktivitätsdetektor",
                    "pt_PT": "Detector de atividade de voz",
                    "ar_SA": "كاشف نشاط الصوت",
                    "vi_VN": "Bộ phát hiện hoạt động giọng nói",
                    "fa_IR": "تشخیص‌دهنده فعالیت صوتی",
                    "id_ID": "Detektor aktivitas suara",
                    "ms_MY": "Pengesan aktiviti suara",
                    "th_TH": "เครื่องตรวจจับกิจกรรมเสียง",
                    "ur_PK": "آواز کی سرگرمی کا پتہ لگانے والا",
                },
                "tooltip": {
                    "en_US": "Which voice activity detector (VAD) to use for speech extraction (if using video / audio as a reference, default=subs_then_webrtc).\nAuditok can sometimes work better in the case of low-quality audio than WebRTC.",
                    "es_ES": "Qué detector de actividad de voz (VAD) usar para la extracción de voz (si se usa video/audio como referencia, predeterminado=subs_then_webrtc).\nAuditok a veces puede funcionar mejor en el caso de audio de baja calidad que WebRTC.",
                    "tr_TR": "Konuşma çıkarımı için hangi ses aktivite dedektörünü (VAD) kullanacağını belirler (video/ses referans olarak kullanılıyorsa, varsayılan=subs_then_webrtc).\nAuditok bazen düşük kaliteli ses durumunda WebRTC'den daha iyi çalışabilir.",
                    "zh_CN": "用于语音提取的语音活动检测器（VAD）（如果使用视频/音频作为参考，默认=subs_then_webrtc）。\n在低质量音频情况下，Auditok有时比WebRTC工作得更好。",
                    "ru_RU": "Какой детектор голосовой активности (VAD) использовать для извлечения речи (если используется видео/аудио в качестве эталона, по умолчанию=subs_then_webrtc).\nAuditok иногда может работать лучше в случае низкокачественного аудио, чем WebRTC.",
                    "pl_PL": "Który detektor aktywności głosu (VAD) używać do ekstrakcji mowy (jeśli używasz wideo/audio jako referencji, domyślnie=subs_then_webrtc).\nAuditok czasami może działać lepiej w przypadku audio niskiej jakości niż WebRTC.",
                    "uk_UA": "Який детектор голосової активності (VAD) використовувати для витягування мовлення (якщо використовується відео/аудіо як еталон, за замовчуванням=subs_then_webrtc).\nAuditok іноді може працювати краще у випадку низькоякісного аудіо, ніж WebRTC.",
                    "ja_JP": "音声抽出に使用する音声活動検出器（VAD）（ビデオ/オーディオを参照として使用する場合、デフォルト=subs_then_webrtc）。\nAuditokは、低品質のオーディオの場合、WebRTCよりもうまく動作することがあります。",
                    "ko_KR": "음성 추출에 사용할 음성 활동 감지기（VAD）（비디오/오디오를 참조로 사용하는 경우, 기본값=subs_then_webrtc）。\nAuditok은 때때로 저품질 오디오의 경우 WebRTC보다 더 잘 작동할 수 있습니다。",
                    "hi_IN": "भाषण निष्कर्षण के लिए कौन सा आवाज गतिविधि डिटेक्टर (VAD) उपयोग करना है (यदि वीडियो/ऑडियो को संदर्भ के रूप में उपयोग कर रहे हैं, डिफ़ॉल्ट=subs_then_webrtc)।\nAuditok कभी-कभी कम गुणवत्ता वाले ऑडियो के मामले में WebRTC से बेहतर काम कर सकता है।",
                    "bn_BD": "স্পিচ এক্সট্র্যাকশনের জন্য কোন ভয়েস অ্যাক্টিভিটি ডিটেক্টর (VAD) ব্যবহার করবেন (যদি ভিডিও/অডিও রেফারেন্স হিসেবে ব্যবহার করেন, ডিফল্ট=subs_then_webrtc)।\nAuditok কখনও কখনও কম মানের অডিওর ক্ষেত্রে WebRTC এর চেয়ে ভাল কাজ করতে পারে।",
                    "it_IT": "Quale rilevatore di attività vocale (VAD) utilizzare per l'estrazione del parlato (se si utilizza video/audio come riferimento, predefinito=subs_then_webrtc).\nAuditok a volte può funzionare meglio nel caso di audio di bassa qualità rispetto a WebRTC.",
                    "fr_FR": "Quel détecteur d'activité vocale (VAD) utiliser pour l'extraction de la parole (si vous utilisez vidéo/audio comme référence, par défaut=subs_then_webrtc).\nAuditok peut parfois mieux fonctionner dans le cas d'audio de faible qualité que WebRTC.",
                    "de_DE": "Welcher Sprachaktivitätsdetektor (VAD) für die Sprachextraktion verwendet werden soll (falls Video/Audio als Referenz verwendet wird, Standard=subs_then_webrtc).\nAuditok kann manchmal bei Audio niedriger Qualität besser funktionieren als WebRTC.",
                    "pt_PT": "Qual detector de atividade de voz (VAD) usar para extração de fala (se usar vídeo/áudio como referência, padrão=subs_then_webrtc).\nAuditok às vezes pode funcionar melhor no caso de áudio de baixa qualidade do que WebRTC.",
                    "ar_SA": "أي كاشف نشاط صوتي (VAD) لاستخدامه لاستخراج الكلام (إذا كنت تستخدم فيديو/صوت كمرجع، افتراضي=subs_then_webrtc).\nيمكن أن يعمل Auditok أحيانًا بشكل أفضل في حالة الصوت منخفض الجودة من WebRTC.",
                    "vi_VN": "Bộ phát hiện hoạt động giọng nói (VAD) nào để sử dụng cho việc trích xuất giọng nói (nếu sử dụng video/âm thanh làm tham chiếu, mặc định=subs_then_webrtc).\nAuditok đôi khi có thể hoạt động tốt hơn trong trường hợp âm thanh chất lượng thấp so với WebRTC.",
                    "fa_IR": "کدام تشخیص‌دهنده فعالیت صوتی (VAD) برای استخراج گفتار استفاده شود (اگر از ویدیو/صدا به عنوان مرجع استفاده می‌کنید، پیش‌فرض=subs_then_webrtc).\nAuditok گاهی اوقات می‌تواند در مورد صدای کیفیت پایین بهتر از WebRTC عمل کند.",
                    "id_ID": "Detektor aktivitas suara (VAD) mana yang digunakan untuk ekstraksi bicara (jika menggunakan video/audio sebagai referensi, default=subs_then_webrtc).\nAuditok terkadang dapat bekerja lebih baik dalam kasus audio berkualitas rendah daripada WebRTC.",
                    "ms_MY": "Pengesan aktiviti suara (VAD) yang manakah untuk digunakan bagi pengekstrakan pertuturan (jika menggunakan video/audio sebagai rujukan, lalai=subs_then_webrtc).\nAuditok kadangkala boleh berfungsi lebih baik dalam kes audio berkualiti rendah berbanding WebRTC.",
                    "th_TH": "เครื่องตรวจจับกิจกรรมเสียง (VAD) ไหนที่จะใช้สำหรับการแยกเสียงพูด (หากใช้วิดีโอ/เสียงเป็นอ้างอิง ค่าเริ่มต้น=subs_then_webrtc)\nAuditok บางครั้งอาจทำงานได้ดีกว่าในกรณีของเสียงคุณภาพต่ำกว่า WebRTC",
                    "ur_PK": "تقریر نکالنے کے لیے کون سا آواز کی سرگرمی کا پتہ لگانے والا (VAD) استعمال کرنا ہے (اگر ویڈیو/آڈیو کو ریفرنس کے طور پر استعمال کر رہے ہیں، ڈیفالٹ=subs_then_webrtc)۔\nAuditok کبھی کبھی کم معیار کی آڈیو کے معاملے میں WebRTC سے بہتر کام کر سکتا ہے۔",
                },
                "argument": "--vad",
                "default": "default",
                "values": [
                    "default",
                    "subs_then_webrtc",
                    "subs_then_auditok",
                    "subs_then_silero",
                    "webrtc",
                    "auditok",
                    "silero",
                ],
                "value_labels": {
                    "default": {
                        "en_US": "Default",
                        "es_ES": "Predeterminado",
                        "tr_TR": "Varsayılan",
                        "zh_CN": "默认",
                        "ru_RU": "По умолчанию",
                        "pl_PL": "Domyślny",
                        "uk_UA": "За замовчуванням",
                        "ja_JP": "デフォルト",
                        "ko_KR": "기본값",
                        "hi_IN": "डिफ़ॉल्ट",
                        "bn_BD": "ডিফল্ট",
                        "it_IT": "Predefinito",
                        "fr_FR": "Par défaut",
                        "de_DE": "Standard",
                        "pt_PT": "Padrão",
                        "ar_SA": "افتراضي",
                        "vi_VN": "Mặc định",
                        "fa_IR": "پیش‌فرض",
                        "id_ID": "Default",
                        "ms_MY": "Lalai",
                        "th_TH": "ค่าเริ่มต้น",
                        "ur_PK": "ڈیفالٹ",
                    },
                    "subs_then_webrtc": {
                        "en_US": "Subs then WebRTC",
                        "es_ES": "Subtítulos y luego WebRTC",
                        "tr_TR": "Önce altyazılar sonra WebRTC",
                        "zh_CN": "字幕然后WebRTC",
                        "ru_RU": "Субтитры, затем WebRTC",
                        "pl_PL": "Napisy, potem WebRTC",
                        "uk_UA": "Субтитри, потім WebRTC",
                        "ja_JP": "字幕からWebRTC",
                        "ko_KR": "자막 후 WebRTC",
                        "hi_IN": "उपशीर्षक फिर WebRTC",
                        "bn_BD": "সাবটাইটেল তারপর WebRTC",
                        "it_IT": "Sottotitoli poi WebRTC",
                        "fr_FR": "Sous-titres puis WebRTC",
                        "de_DE": "Untertitel dann WebRTC",
                        "pt_PT": "Legendas e depois WebRTC",
                        "ar_SA": "الترجمات ثم WebRTC",
                        "vi_VN": "Phụ đề rồi WebRTC",
                        "fa_IR": "زیرنویس‌ها سپس WebRTC",
                        "id_ID": "Subtitle lalu WebRTC",
                        "ms_MY": "Sarikata kemudian WebRTC",
                        "th_TH": "คำบรรยายแล้ว WebRTC",
                        "ur_PK": "سب ٹائٹل پھر WebRTC",
                    },
                    "subs_then_auditok": {
                        "en_US": "Subs then Auditok",
                        "es_ES": "Subtítulos y luego Auditok",
                        "tr_TR": "Önce altyazılar sonra Auditok",
                        "zh_CN": "字幕然后Auditok",
                        "ru_RU": "Субтитры, затем Auditok",
                        "pl_PL": "Napisy, potem Auditok",
                        "uk_UA": "Субтитри, потім Auditok",
                        "ja_JP": "字幕からAuditok",
                        "ko_KR": "자막 후 Auditok",
                        "hi_IN": "उपशीर्षक फिर Auditok",
                        "bn_BD": "সাবটাইটেল তারপর Auditok",
                        "it_IT": "Sottotitoli poi Auditok",
                        "fr_FR": "Sous-titres puis Auditok",
                        "de_DE": "Untertitel dann Auditok",
                        "pt_PT": "Legendas e depois Auditok",
                        "ar_SA": "الترجمات ثم Auditok",
                        "vi_VN": "Phụ đề rồi Auditok",
                        "fa_IR": "زیرنویس‌ها سپس Auditok",
                        "id_ID": "Subtitle lalu Auditok",
                        "ms_MY": "Sarikata kemudian Auditok",
                        "th_TH": "คำบรรยายแล้ว Auditok",
                        "ur_PK": "سب ٹائٹل پھر Auditok",
                    },
                    "subs_then_silero": {
                        "en_US": "Subs then Silero",
                        "es_ES": "Subtítulos y luego Silero",
                        "tr_TR": "Önce altyazılar sonra Silero",
                        "zh_CN": "字幕然后Silero",
                        "ru_RU": "Субтитры, затем Silero",
                        "pl_PL": "Napisy, potem Silero",
                        "uk_UA": "Субтитри, потім Silero",
                        "ja_JP": "字幕からSilero",
                        "ko_KR": "자막 후 Silero",
                        "hi_IN": "उपशीर्षक फिर Silero",
                        "bn_BD": "সাবটাইটেল তারপর Silero",
                        "it_IT": "Sottotitoli poi Silero",
                        "fr_FR": "Sous-titres puis Silero",
                        "de_DE": "Untertitel dann Silero",
                        "pt_PT": "Legendas e depois Silero",
                        "ar_SA": "الترجمات ثم Silero",
                        "vi_VN": "Phụ đề rồi Silero",
                        "fa_IR": "زیرنویس‌ها سپس Silero",
                        "id_ID": "Subtitle lalu Silero",
                        "ms_MY": "Sarikata kemudian Silero",
                        "th_TH": "คำบรรยายแล้ว Silero",
                        "ur_PK": "سب ٹائٹل پھر Silero",
                    },
                    "webrtc": "WebRTC",
                    "auditok": "Auditok",
                    "silero": "Silero",
                },
            },
        },
    },
    "alass": {
        "version": "2.0",
        "description": {
            "en_US": "Automatic Language-Agnostic Subtitle Synchronization",
            "es_ES": "Sincronización Automática de Subtítulos Agnóstica del Idioma",
            "tr_TR": "Otomatik Dil Bağımsız Altyazı Senkronizasyonu",
            "zh_CN": "自动语言无关字幕同步",
            "ru_RU": "Автоматическая языково-независимая синхронизация субтитров",
            "pl_PL": "Automatyczna synchronizacja napisów niezależna od języka",
            "uk_UA": "Автоматична мовно-незалежна синхронізація субтитрів",
            "ja_JP": "自動言語非依存字幕同期",
            "ko_KR": "자동 언어 비의존적 자막 동기화",
            "hi_IN": "स्वचालित भाषा-अज्ञेयवादी उपशीर्षक सिंक्रनाइज़ेशन",
            "bn_BD": "স্বয়ংক্রিয় ভাষা-অজ্ঞেয়বাদী সাবটাইটেল সিঙ্ক্রোনাইজেশন",
            "it_IT": "Sincronizzazione automatica dei sottotitoli indipendente dalla lingua",
            "fr_FR": "Synchronisation automatique de sous-titres indépendante de la langue",
            "de_DE": "Automatische sprachunabhängige Untertitelsynchronisation",
            "pt_PT": "Sincronização automática de legendas independente de idioma",
            "ar_SA": "مزامنة الترجمات التلقائية المستقلة عن اللغة",
            "vi_VN": "Đồng bộ phụ đề tự động không phụ thuộc vào ngôn ngữ",
            "fa_IR": "همگام‌سازی خودکار زیرنویس مستقل از زبان",
            "id_ID": "Sinkronisasi subtitle otomatis yang tidak bergantung pada bahasa",
            "ms_MY": "Segerak sarikata automatik yang tidak bergantung pada bahasa",
            "th_TH": "การซิงค์คำบรรยายอัตโนมัติที่ไม่ขึ้นกับภาษา",
            "ur_PK": "خودکار زبان سے آزاد سب ٹائٹل سنکرونائزیشن",
        },
        "github": "https://github.com/kaegi/alass",
        "documentation": "https://github.com/kaegi/alass/blob/master/documentation/slides.pdf",
        "supported_formats": [".srt", ".ass", ".ssa", ".sub", ".idx"],
        "supports_subtitle_as_reference": True,
        "type": "executable",
        "executable": {
            "Windows": get_resource_path(
                "autosubsyncapp.resources.alass-bin", "alass-cli.exe"
            ),
            "Linux": get_resource_path(
                "autosubsyncapp.resources.alass-bin", "alass-linux64"
            ),
            "Darwin": "alass-cli",
        },
        "cmd_structure": ["{reference}", "{subtitle}", "{output}"],
        "options": {
            "check_video_for_subtitles": {
                "type": "checkbox",
                "label": {
                    "en_US": "Use embedded subtitles in video",
                    "es_ES": "Usar subtítulos incrustados en el vídeo",
                    "tr_TR": "Videodaki gömülü altyazıları kullan",
                    "zh_CN": "使用视频中的内嵌字幕",
                    "ru_RU": "Использовать встроенные субтитры в видео",
                    "pl_PL": "Użyj osadzonych napisów w wideo",
                    "uk_UA": "Використовувати вбудовані субтитри у відео",
                    "ja_JP": "ビデオ内の埋め込み字幕を使用",
                    "ko_KR": "비디오에 내장된 자막 사용",
                    "hi_IN": "वीडियो में एम्बेडेड उपशीर्षक का उपयोग करें",
                    "bn_BD": "ভিডিওতে এম্বেড করা সাবটাইটেল ব্যবহার করুন",
                    "it_IT": "Usa i sottotitoli incorporati nel video",
                    "fr_FR": "Utiliser les sous-titres intégrés dans la vidéo",
                    "de_DE": "Eingebettete Untertitel im Video verwenden",
                    "pt_PT": "Usar legendas incorporadas no vídeo",
                    "ar_SA": "استخدم الترجمات المضمنة في الفيديو",
                    "vi_VN": "Sử dụng phụ đề nhúng trong video",
                    "fa_IR": "استفاده از زیرنویس‌های جاسازی‌شده در ویدیو",
                    "id_ID": "Gunakan subtitle tertanam di video",
                    "ms_MY": "Guna sarikata terbenam dalam video",
                    "th_TH": "ใช้คำบรรยายที่ฝังในวิดีโอ",
                    "ur_PK": "ویڈیو میں ایمبیڈڈ سب ٹائٹلز استعمال کریں",
                },
                "tooltip": {
                    "en_US": "Extract the embedded subtitles in the video and perform synchronization with these subtitles.",
                    "es_ES": "Extrae los subtítulos incrustados en el vídeo y realiza la sincronización con estos subtítulos.",
                    "tr_TR": "Videodaki gömülü altyazıları çıkarır ve bu altyazılarla senkronizasyon yapar.",
                    "zh_CN": "提取视频中的内嵌字幕并与这些字幕进行同步。",
                    "ru_RU": "Извлекает встроенные субтитры из видео и выполняет синхронизацию с ними.",
                    "pl_PL": "Wyodrębnia osadzone napisy z wideo i synchronizuje z nimi.",
                    "uk_UA": "Витягує вбудовані субтитри з відео та виконує синхронізацію з ними.",
                    "ja_JP": "ビデオ内の埋め込み字幕を抽出し、それらの字幕と同期します。",
                    "ko_KR": "비디오에 내장된 자막을 추출하고 해당 자막과 동기화합니다.",
                    "hi_IN": "वीडियो में एम्बेडेड उपशीर्षकों को निकालें और उनके साथ सिंक्रनाइज़ करें।",
                    "bn_BD": "ভিডিওতে এম্বেড করা সাবটাইটেল বের করুন এবং সেগুলোর সাথে সিঙ্ক করুন।",
                    "it_IT": "Estrae i sottotitoli incorporati nel video ed esegue la sincronizzazione con questi sottotitoli.",
                    "fr_FR": "Extrait les sous-titres intégrés dans la vidéo et effectue la synchronisation avec ces sous-titres.",
                    "de_DE": "Extrahiert die eingebetteten Untertitel aus dem Video und synchronisiert mit diesen Untertiteln.",
                    "pt_PT": "Extrai as legendas incorporadas no vídeo e sincroniza com essas legendas.",
                    "ar_SA": "يستخرج الترجمات المضمنة في الفيديو ويقوم بمزامنتها مع هذه الترجمات.",
                    "vi_VN": "Trích xuất phụ đề nhúng trong video và đồng bộ hóa với các phụ đề này.",
                    "fa_IR": "زیرنویس‌های جاسازی‌شده در ویدیو را استخراج کرده و با آن‌ها همگام‌سازی می‌کند.",
                    "id_ID": "Ekstrak subtitle tertanam di video dan lakukan sinkronisasi dengan subtitle tersebut.",
                    "ms_MY": "Ekstrak sarikata terbenam dalam video dan lakukan penyegerakan dengan sarikata tersebut.",
                    "th_TH": "แยกคำบรรยายที่ฝังในวิดีโอและซิงค์กับคำบรรยายนั้น",
                    "ur_PK": "ویڈیو میں ایمبیڈڈ سب ٹائٹلز نکالیں اور ان کے ساتھ سنکرونائز کریں۔",
                },
                "default": True,
            },
            "disable_fps_guessing": {
                "type": "checkbox",
                "label": {
                    "en_US": "Disable FPS guessing",
                    "es_ES": "Desactivar estimación de FPS",
                    "tr_TR": "FPS tahmini devre dışı bırak",
                    "zh_CN": "禁用帧率猜测",
                    "ru_RU": "Отключить угадывание FPS",
                    "pl_PL": "Wyłącz zgadywanie FPS",
                    "uk_UA": "Вимкнути вгадування FPS",
                    "ja_JP": "FPS推測を無効にする",
                    "ko_KR": "FPS 추측 비활성화",
                    "hi_IN": "FPS अनुमान अक्षम करें",
                    "bn_BD": "FPS অনুমান নিষ্ক্রিয় করুন",
                    "it_IT": "Disabilita previsione FPS",
                    "fr_FR": "Désactiver l'estimation des FPS",
                    "de_DE": "FPS-Schätzung deaktivieren",
                    "pt_PT": "Desativar suposição de FPS",
                    "ar_SA": "تعطيل تخمين معدل الإطارات",
                    "vi_VN": "Tắt đoán tốc độ khung hình",
                    "fa_IR": "غیرفعال کردن حدس FPS",
                    "id_ID": "Nonaktifkan penebakan FPS",
                    "ms_MY": "Lumpuhkan tekaan FPS",
                    "th_TH": "ปิดการคาดเดาอัตราเฟรม",
                    "ur_PK": "FPS اندازہ غیر فعال کریں",
                },
                "tooltip": {
                    "en_US": "Disables guessing and correcting of framerate differences between reference file and input file.",
                    "es_ES": "Desactiva la estimación y corrección de diferencias en la velocidad de fotogramas entre el archivo de referencia y el archivo de entrada.",
                    "tr_TR": "Referans dosya ve girdi dosyası arasındaki kare hızı farklılıklarının tahmin edilmesini ve düzeltilmesini devre dışı bırakır.",
                    "zh_CN": "禁用猜测和校正参考文件和输入文件之间的帧率差异。",
                    "ru_RU": "Отключает угадывание и исправление различий частоты кадров между эталонным файлом и входным файлом.",
                    "pl_PL": "Wyłącza zgadywanie i korygowanie różnic w liczbie klatek na sekundę między plikiem referencyjnym a plikiem wejściowym.",
                    "uk_UA": "Вимикає вгадування та виправлення відмінностей частоти кадрів між еталонним файлом і вхідним файлом.",
                    "ja_JP": "参照ファイルと入力ファイル間のフレームレートの違いの推測と修正を無効にします。",
                    "ko_KR": "참조 파일과 입력 파일 간의 프레임 레이트 차이를 추측하고 수정하는 기능을 비활성화합니다.",
                    "hi_IN": "संदर्भ फ़ाइल और इनपुट फ़ाइल के बीच फ्रेमरेट अंतर का अनुमान और सुधार अक्षम करता है।",
                    "bn_BD": "রেফারেন্স ফাইল এবং ইনপুট ফাইলের মধ্যে ফ্রেমরেট পার্থক্যের অনুমান এবং সংশোধন নিষ্ক্রিয় করে।",
                    "it_IT": "Disabilita la previsione e la correzione delle differenze di framerate tra il file di riferimento e il file di input.",
                    "fr_FR": "Désactive l'estimation et la correction des différences de fréquence d'images entre le fichier de référence et le fichier d'entrée.",
                    "de_DE": "Deaktiviert das Erraten und Korrigieren von Bildfrequenzunterschieden zwischen Referenzdatei und Eingabedatei.",
                    "pt_PT": "Desativa a suposição e correção de diferenças de taxa de quadros entre o ficheiro de referência e o ficheiro de entrada.",
                    "ar_SA": "يعطل تخمين وتصحيح اختلافات معدل الإطارات بين ملف المرجع وملف الإدخال.",
                    "vi_VN": "Tắt đoán và sửa sự khác biệt tốc độ khung hình giữa tệp tham chiếu và tệp đầu vào.",
                    "fa_IR": "حدس زدن و تصحیح تفاوت‌های نرخ فریم بین فایل مرجع و فایل ورودی را غیرفعال می‌کند.",
                    "id_ID": "Menonaktifkan penebakan dan koreksi perbedaan framerate antara file referensi dan file input.",
                    "ms_MY": "Melumpuhkan tekaan dan pembetulan perbezaan kadar bingkai antara fail rujukan dan fail input.",
                    "th_TH": "ปิดการคาดเดาและการแก้ไขความแตกต่างของอัตราเฟรมระหว่างไฟล์อ้างอิงและไฟล์อินพุต",
                    "ur_PK": "حوالہ فائل اور ان پٹ فائل کے درمیان فریم ریٹ کے فرق کا اندازہ لگانا اور درست کرنا غیر فعال کرتا ہے۔",
                },
                "argument": "--disable-fps-guessing",
                "default": False,
            },
            "disable_speed_optimization": {
                "type": "checkbox",
                "label": {
                    "en_US": "Disable speed optimization",
                    "es_ES": "Desactivar optimización de velocidad",
                    "tr_TR": "Hız optimizasyonunu devre dışı bırak",
                    "zh_CN": "禁用速度优化",
                    "ru_RU": "Отключить оптимизацию скорости",
                    "pl_PL": "Wyłącz optymalizację prędkości",
                    "uk_UA": "Вимкнути оптимізацію швидкості",
                    "ja_JP": "速度最適化を無効にする",
                    "ko_KR": "속도 최적화 비활성화",
                    "hi_IN": "गति अनुकूलन अक्षम करें",
                    "bn_BD": "গতি অপ্টিমাইজেশন নিষ্ক্রিয় করুন",
                    "it_IT": "Disabilita ottimizzazione velocità",
                    "fr_FR": "Désactiver l'optimisation de la vitesse",
                    "de_DE": "Geschwindigkeitsoptimierung deaktivieren",
                    "pt_PT": "Desativar otimização de velocidade",
                    "ar_SA": "تعطيل تحسين السرعة",
                    "vi_VN": "Tắt tối ưu hóa tốc độ",
                    "fa_IR": "غیرفعال کردن بهینه‌سازی سرعت",
                    "id_ID": "Nonaktifkan optimasi kecepatan",
                    "ms_MY": "Lumpuhkan pengoptimuman kelajuan",
                    "th_TH": "ปิดการเพิ่มประสิทธิภาพความเร็ว",
                    "ur_PK": "رفتار کی بہتری غیر فعال کریں",
                },
                "tooltip": {
                    "en_US": "Disable speed optimization for better accuracy. This will increase the processing time.",
                    "es_ES": "Desactiva la optimización de velocidad para mejorar la precisión. Esto aumentará el tiempo de procesamiento.",
                    "tr_TR": "Daha iyi doğruluk için hız optimizasyonunu devre dışı bırakın. Bu, işlem süresini artıracaktır.",
                    "zh_CN": "禁用速度优化以提高准确性。这将增加处理时间。",
                    "ru_RU": "Отключите оптимизацию скорости для лучшей точности. Это увеличит время обработки.",
                    "pl_PL": "Wyłącz optymalizację prędkości dla lepszej dokładności. Wydłuży to czas przetwarzania.",
                    "uk_UA": "Вимкніть оптимізацію швидкості для кращої точності. Це збільшить час обробки.",
                    "ja_JP": "精度を向上させるために速度最適化を無効にします。これにより処理時間が長くなります。",
                    "ko_KR": "더 나은 정확도를 위해 속도 최적화를 비활성화합니다. 이렇게 하면 처리 시간이 증가합니다.",
                    "hi_IN": "बेहतर सटीकता के लिए गति अनुकूलन अक्षम करें। यह प्रसंस्करण समय बढ़ा देगा।",
                    "bn_BD": "আরো ভাল নির্ভুলতার জন্য গতি অপ্টিমাইজেশন নিষ্ক্রিয় করুন। এটি প্রক্রিয়াকরণের সময় বাড়িয়ে দেবে।",
                    "it_IT": "Disabilita l'ottimizzazione della velocità per una maggiore precisione. Questo aumenterà il tempo di elaborazione.",
                    "fr_FR": "Désactivez l'optimisation de la vitesse pour une meilleure précision. Cela augmentera le temps de traitement.",
                    "de_DE": "Deaktivieren Sie die Geschwindigkeitsoptimierung für eine bessere Genauigkeit. Dies erhöht die Verarbeitungszeit.",
                    "pt_PT": "Desative a otimização de velocidade para obter melhor precisão. Isto aumentará o tempo de processamento.",
                    "ar_SA": "قم بتعطيل تحسين السرعة للحصول على دقة أفضل. سيؤدي هذا إلى زيادة وقت المعالجة.",
                    "vi_VN": "Tắt tối ưu hóa tốc độ để có độ chính xác tốt hơn. Điều này sẽ làm tăng thời gian xử lý.",
                    "fa_IR": "بهینه‌سازی سرعت را برای دقت بهتر غیرفعال کنید. این زمان پردازش را افزایش می‌دهد.",
                    "id_ID": "Nonaktifkan optimasi kecepatan untuk akurasi yang lebih baik. Ini akan meningkatkan waktu pemrosesan.",
                    "ms_MY": "Lumpuhkan pengoptimuman kelajuan untuk ketepatan yang lebih baik. Ini akan meningkatkan masa pemprosesan.",
                    "th_TH": "ปิดการเพิ่มประสิทธิภาพความเร็วเพื่อความแม่นยำที่ดีขึ้น ซึ่งจะเพิ่มเวลาการประมวลผล",
                    "ur_PK": "بہتر درستگی کے لیے رفتار کی بہتری کو غیر فعال کریں۔ یہ پروسیسنگ کا وقت بڑھا دے گا۔",
                },
                "argument": "--speed-optimization=0",
                "default": False,
            },
            "split_penalty": {
                "type": "slider",
                "label": {
                    "en_US": "Split penalty",
                    "es_ES": "Penalización por división",
                    "tr_TR": "Bölme cezası",
                    "zh_CN": "分割惩罚",
                    "ru_RU": "Штраф за разделение",
                    "pl_PL": "Kara za podział",
                    "uk_UA": "Штраф за розділення",
                    "ja_JP": "分割ペナルティ",
                    "ko_KR": "분할 패널티",
                    "hi_IN": "विभाजन दंड",
                    "bn_BD": "স্প্লিট পেনাল্টি",
                    "it_IT": "Penalità di divisione",
                    "fr_FR": "Pénalité de division",
                    "de_DE": "Teilungsstrafe",
                    "pt_PT": "Penalidade de divisão",
                    "ar_SA": "عقوبة التقسيم",
                    "vi_VN": "Phạt phân tách",
                    "fa_IR": "جریمه تقسیم",
                    "id_ID": "Penalti pemisahan",
                    "ms_MY": "Penalti pemisahan",
                    "th_TH": "บทลงโทษการแบ่ง",
                    "ur_PK": "تقسیم کی سزا",
                },
                "argument": "--split-penalty",
                "tooltip": {
                    "en_US": "Penalty for splitting subtitles during alignment\n(Default: 7, Recommended: 5-20, No splits: -1)",
                    "es_ES": "Penalización por dividir subtítulos durante la alineación\n(Predeterminado: 7, Recomendado: 5-20, Sin divisiones: -1)",
                    "tr_TR": "Hizalama sırasında altyazıları bölme cezası\n(Varsayılan: 7, Önerilen: 5-20, Bölme yok: -1)",
                    "zh_CN": "在对齐过程中分割字幕的惩罚值\n（默认：7，推荐：5-20，不分割：-1）",
                    "ru_RU": "Штраф за разделение субтитров во время выравнивания\n(По умолчанию: 7, Рекомендуется: 5-20, Без разделения: -1)",
                    "pl_PL": "Kara za dzielenie napisów podczas wyrównywania\n(Domyślnie: 7, Zalecane: 5-20, Brak podziałów: -1)",
                    "uk_UA": "Штраф за розділення субтитрів під час вирівнювання\n(За замовчуванням: 7, Рекомендовано: 5-20, Без розділення: -1)",
                    "ja_JP": "アライメント中に字幕を分割するためのペナルティ\n（デフォルト：7、推奨：5-20、分割なし：-1）",
                    "ko_KR": "정렬 중 자막 분할에 대한 패널티\n(기본값: 7, 권장: 5-20, 분할 없음: -1)",
                    "hi_IN": "संरेखण के दौरान उपशीर्षकों को विभाजित करने का दंड\n(डिफ़ॉल्ट: 7, अनुशंसित: 5-20, कोई विभाजन नहीं: -1)",
                    "bn_BD": "অ্যালাইনমেন্ট চলাকালীন সাবটাইটেল বিভাজনের জন্য পেনাল্টি\n(ডিফল্ট: 7, প্রস্তাবিত: 5-20, বিভাজন নেই: -1)",
                    "it_IT": "Penalità per la divisione dei sottotitoli durante l'allineamento\n(Predefinito: 7, Consigliato: 5-20, Nessuna divisione: -1)",
                    "fr_FR": "Pénalité pour la division des sous-titres pendant l'alignement\n(Par défaut : 7, Recommandé : 5-20, Pas de divisions : -1)",
                    "de_DE": "Strafe für die Teilung von Untertiteln während der Ausrichtung\n(Standard: 7, Empfohlen: 5-20, Keine Teilung: -1)",
                    "pt_PT": "Penalidade por dividir legendas durante o alinhamento\n(Padrão: 7, Recomendado: 5-20, Sem divisões: -1)",
                    "ar_SA": "عقوبة تقسيم الترجمات أثناء المحاذاة\n(افتراضي: 7، موصى به: 5-20، بدون تقسيم: -1)",
                    "vi_VN": "Hình phạt cho việc phân tách phụ đề trong quá trình căn chỉnh\n(Mặc định: 7, Khuyến nghị: 5-20, Không phân tách: -1)",
                    "fa_IR": "جریمه تقسیم زیرنویس‌ها در حین تراز کردن\n(پیش‌فرض: 7، پیشنهادی: 5-20، بدون تقسیم: -1)",
                    "id_ID": "Penalti untuk memisahkan subtitle selama penyelarasan\n(Default: 7, Direkomendasikan: 5-20, Tanpa pemisahan: -1)",
                    "ms_MY": "Penalti untuk memisahkan sarikata semasa penjajaran\n(Lalai: 7, Disyorkan: 5-20, Tiada pemisahan: -1)",
                    "th_TH": "บทลงโทษสำหรับการแบ่งคำบรรยายระหว่างการปรับแนว\n(ค่าเริ่มต้น: 7, แนะนำ: 5-20, ไม่แบ่ง: -1)",
                    "ur_PK": "ہم آہنگی کے دوران سب ٹائٹلز کو تقسیم کرنے کی سزا\n(ڈیفالٹ: 7، تجویز کردہ: 5-20، کوئی تقسیم نہیں: -1)",
                },
                "no_split_argument": "--no-split",
                "range": [-1, 100],
                "default": 7,
            },
        },
    },
    "autosubsync": {
        "version": get_version_info("autosubsync"),
        "description": {
            "en_US": "Automatically synchronize subtitles with audio using machine learning",
            "es_ES": "Sincroniza automáticamente subtítulos con audio usando aprendizaje automático",
            "tr_TR": "Makine öğrenmesi kullanarak altyazıları sesle otomatik olarak senkronize edin",
            "zh_CN": "使用机器学习自动将字幕与音频同步",
            "ru_RU": "Автоматически синхронизируйте субтитры с аудио с помощью машинного обучения",
            "pl_PL": "Automatycznie synchronizuj napisy z dźwiękiem za pomocą uczenia maszynowego",
            "uk_UA": "Автоматично синхронізуйте субтитри з аудіо за допомогою машинного навчання",
            "ja_JP": "機械学習を使用して字幕を音声と自動的に同期します",
            "ko_KR": "머신러닝을 사용하여 자막을 오디오와 자동으로 동기화합니다",
            "hi_IN": "मशीन लर्निंग का उपयोग करके स्वचालित रूप से ऑडियो के साथ उपशीर्षक सिंक्रनाइज़ करें",
            "bn_BD": "মেশিন লার্নিং ব্যবহার করে স্বয়ংক্রিয়ভাবে অডিওর সাথে সাবটাইটেল সিঙ্ক করুন",
            "it_IT": "Sincronizza automaticamente i sottotitoli con l'audio utilizzando l'apprendimento automatico",
            "fr_FR": "Synchronisez automatiquement les sous-titres avec l'audio en utilisant l'apprentissage automatique",
            "de_DE": "Synchronisieren Sie Untertitel automatisch mit Audio mithilfe von maschinellem Lernen",
            "pt_PT": "Sincronize automaticamente legendas com áudio usando aprendizado de máquina",
            "ar_SA": "قم بمزامنة الترجمات مع الصوت تلقائيًا باستخدام التعلم الآلي",
            "vi_VN": "Tự động đồng bộ phụ đề với âm thanh bằng cách sử dụng máy học",
            "fa_IR": "با استفاده از یادگیری ماشین، زیرنویس‌ها را به طور خودکار با صدا همگام‌سازی کنید",
            "id_ID": "Sinkronkan subtitle dengan audio secara otomatis menggunakan pembelajaran mesin",
            "ms_MY": "Segerakkan sarikata dengan audio secara automatik menggunakan pembelajaran mesin",
            "th_TH": "ซิงค์คำบรรยายกับเสียงโดยอัตโนมัติโดยใช้การเรียนรู้ของเครื่อง",
            "ur_PK": "مشین لرننگ کا استعمال کرتے ہوئے خودکار طور پر آڈیو کے ساتھ سب ٹائٹلز کو سنکرونائز کریں",
        },
        "github": "https://github.com/oseiskar/autosubsync",
        "documentation": "https://github.com/oseiskar/autosubsync?tab=readme-ov-file#usage",
        "supported_formats": [".srt"],
        "supports_subtitle_as_reference": False,
        "type": "module",
        "module": "call_autosubsync",
        "cmd_structure": ["{reference}", "{subtitle}", "{output}"],
        "options": {
            "spacer1": {
                "type": "spacer",
                "value": 2,
            },
            "check_video_for_subtitles": {
                "type": "checkbox",
                "label": {
                    "en_US": "Use embedded subtitles in video",
                    "es_ES": "Usar subtítulos incrustados en el vídeo",
                    "tr_TR": "Videodaki gömülü altyazıları kullan",
                    "zh_CN": "使用视频中的内嵌字幕",
                    "ru_RU": "Использовать встроенные субтитры в видео",
                    "pl_PL": "Użyj osadzonych napisów w wideo",
                    "uk_UA": "Використовувати вбудовані субтитри у відео",
                    "ja_JP": "ビデオ内の埋め込み字幕を使用",
                    "ko_KR": "비디오에 내장된 자막 사용",
                    "hi_IN": "वीडियो में एम्बेडेड उपशीर्षक का उपयोग करें",
                    "bn_BD": "ভিডিওতে এম্বেড করা সাবটাইটেল ব্যবহার করুন",
                    "it_IT": "Usa i sottotitoli incorporati nel video",
                    "fr_FR": "Utiliser les sous-titres intégrés dans la vidéo",
                    "de_DE": "Eingebettete Untertitel im Video verwenden",
                    "pt_PT": "Usar legendas incorporadas no vídeo",
                    "ar_SA": "استخدم الترجمات المضمنة في الفيديو",
                    "vi_VN": "Sử dụng phụ đề nhúng trong video",
                    "fa_IR": "استفاده از زیرنویس‌های جاسازی‌شده در ویدیو",
                    "id_ID": "Gunakan subtitle tertanam di video",
                    "ms_MY": "Guna sarikata terbenam dalam video",
                    "th_TH": "ใช้คำบรรยายที่ฝังในวิดีโอ",
                    "ur_PK": "ویڈیو میں ایمبیڈڈ سب ٹائٹلز استعمال کریں",
                },
                "tooltip": {
                    "en_US": "Extract the embedded subtitles in the video and perform synchronization with these subtitles.",
                    "es_ES": "Extrae los subtítulos incrustados en el vídeo y realiza la sincronización con estos subtítulos.",
                    "tr_TR": "Videodaki gömülü altyazıları çıkarır ve bu altyazılarla senkronizasyon yapar.",
                    "zh_CN": "提取视频中的内嵌字幕并与这些字幕进行同步。",
                    "ru_RU": "Извлекает встроенные субтитры из видео и выполняет синхронизацию с ними.",
                    "pl_PL": "Wyodrębnia osadzone napisy z wideo i synchronizuje z nimi.",
                    "uk_UA": "Витягує вбудовані субтитри з відео та виконує синхронізацію з ними.",
                    "ja_JP": "ビデオ内の埋め込み字幕を抽出し、それらの字幕と同期します。",
                    "ko_KR": "비디오에 내장된 자막을 추출하고 해당 자막과 동기화합니다.",
                    "hi_IN": "वीडियो में एम्बेडेड उपशीर्षकों को निकालें और उनके साथ सिंक्रनाइज़ करें।",
                    "bn_BD": "ভিডিওতে এম্বেড করা সাবটাইটেল বের করুন এবং সেগুলোর সাথে সিঙ্ক করুন।",
                    "it_IT": "Estrae i sottotitoli incorporati nel video ed esegue la sincronizzazione con questi sottotitoli.",
                    "fr_FR": "Extrait les sous-titres intégrés dans la vidéo et effectue la synchronisation avec ces sous-titres.",
                    "de_DE": "Extrahiert die eingebetteten Untertitel aus dem Video und synchronisiert mit diesen Untertiteln.",
                    "pt_PT": "Extrai as legendas incorporadas no vídeo e sincroniza com essas legendas.",
                    "ar_SA": "يستخرج الترجمات المضمنة في الفيديو ويقوم بمزامنتها مع هذه الترجمات.",
                    "vi_VN": "Trích xuất phụ đề nhúng trong video và đồng bộ hóa với các phụ đề này.",
                    "fa_IR": "زیرنویس‌های جاسازی‌شده در ویدیو را استخراج کرده و با آن‌ها همگام‌سازی می‌کند.",
                    "id_ID": "Ekstrak subtitle tertanam di video dan lakukan sinkronisasi dengan subtitle tersebut.",
                    "ms_MY": "Ekstrak sarikata terbenam dalam video dan lakukan penyegerakan dengan sarikata tersebut.",
                    "th_TH": "แยกคำบรรยายที่ฝังในวิดีโอและซิงค์กับคำบรรยายนั้น",
                    "ur_PK": "ویڈیو میں ایمبیڈڈ سب ٹائٹلز نکالیں اور ان کے ساتھ سنکرونائز کریں۔",
                },
                "default": True,
            },
            "spacer2": {
                "type": "spacer",
                "value": 9,
            },
            "max_shift_secs": {
                "type": "slider",
                "label": {
                    "en_US": "Maximum shift (seconds)",
                    "es_ES": "Desplazamiento máximo (segundos)",
                    "tr_TR": "Maksimum kaydırma (saniye)",
                    "zh_CN": "最大位移（秒）",
                    "ru_RU": "Максимальный сдвиг (секунды)",
                    "pl_PL": "Maksymalne przesunięcie (sekundy)",
                    "uk_UA": "Максимальний зсув (секунди)",
                    "ja_JP": "最大シフト（秒）",
                    "ko_KR": "최대 이동 (초)",
                    "hi_IN": "अधिकतम शिफ्ट (सेकंड)",
                    "bn_BD": "সর্বাধিক শিফট (সেকেন্ড)",
                    "it_IT": "Spostamento massimo (secondi)",
                    "fr_FR": "Décalage maximum (secondes)",
                    "de_DE": "Maximale Verschiebung (Sekunden)",
                    "pt_PT": "Deslocamento máximo (segundos)",
                    "ar_SA": "الإزاحة القصوى (ثواني)",
                    "vi_VN": "Dịch chuyển tối đa (giây)",
                    "fa_IR": "حداکثر جابجایی (ثانیه)",
                    "id_ID": "Pergeseran maksimum (detik)",
                    "ms_MY": "Anjakan maksimum (saat)",
                    "th_TH": "การเลื่อนสูงสุด (วินาที)",
                    "ur_PK": "زیادہ سے زیادہ شفٹ (سیکنڈز)",
                },
                "tooltip": {
                    "en_US": "Maximum subtitle shift in seconds (default 20)",
                    "es_ES": "Desplazamiento máximo de subtítulos en segundos (predeterminado 20)",
                    "tr_TR": "Saniye cinsinden maksimum altyazı kaydırma (varsayılan 20)",
                    "zh_CN": "字幕最大位移秒数（默认20）",
                    "ru_RU": "Максимальный сдвиг субтитров в секундах (по умолчанию 20)",
                    "pl_PL": "Maksymalne przesunięcie napisów w sekundach (domyślnie 20)",
                    "uk_UA": "Максимальний зсув субтитрів у секундах (за замовчуванням 20)",
                    "ja_JP": "字幕の最大シフト秒数（デフォルト20）",
                    "ko_KR": "초 단위의 최대 자막 이동 (기본값 20)",
                    "hi_IN": "सेकंड में अधिकतम उपशीर्षक शिफ्ट (डिफ़ॉल्ट 20)",
                    "bn_BD": "সেকেন্ডে সর্বাধিক সাবটাইটেল শিফট (ডিফল্ট 20)",
                    "it_IT": "Spostamento massimo dei sottotitoli in secondi (predefinito 20)",
                    "fr_FR": "Décalage maximum des sous-titres en secondes (par défaut 20)",
                    "de_DE": "Maximale Untertitelverschiebung in Sekunden (Standard 20)",
                    "pt_PT": "Deslocamento máximo de legendas em segundos (padrão 20)",
                    "ar_SA": "الإزاحة القصوى للترجمات بالثواني (الافتراضي 20)",
                    "vi_VN": "Dịch chuyển phụ đề tối đa tính bằng giây (mặc định 20)",
                    "fa_IR": "حداکثر جابجایی زیرنویس به ثانیه (پیش‌فرض 20)",
                    "id_ID": "Pergeseran maksimum subtitle dalam detik (default 20)",
                    "ms_MY": "Anjakan maksimum sarikata dalam saat (lalai 20)",
                    "th_TH": "การเลื่อนคำบรรยายสูงสุดเป็นวินาที (ค่าเริ่มต้น 20)",
                    "ur_PK": "سیکنڈز میں زیادہ سے زیادہ سب ٹائٹل شفٹ (ڈیفالٹ 20)",
                },
                "argument": "--max_shift_secs",
                "range": [1, 120],
                "default": 20,
            },
            "parallelism": {
                "type": "slider",
                "label": {
                    "en_US": "Parallelism",
                    "es_ES": "Paralelismo",
                    "tr_TR": "Paralellik",
                    "zh_CN": "并行度",
                    "ru_RU": "Параллелизм",
                    "pl_PL": "Równoległość",
                    "uk_UA": "Паралелізм",
                    "ja_JP": "並列処理",
                    "ko_KR": "병렬 처리",
                    "hi_IN": "समानांतरता",
                    "bn_BD": "সমান্তরালতা",
                    "it_IT": "Parallelismo",
                    "fr_FR": "Parallélisme",
                    "de_DE": "Parallelität",
                    "pt_PT": "Paralelismo",
                    "ar_SA": "التوازي",
                    "vi_VN": "Xử lý song song",
                    "fa_IR": "پردازش موازی",
                    "id_ID": "Paralelisme",
                    "ms_MY": "Keselarian",
                    "th_TH": "การประมวลผลแบบขนาน",
                    "ur_PK": "متوازی پن",
                },
                "tooltip": {
                    "en_US": "Number of parallel worker processes (default 3)",
                    "es_ES": "Número de procesos de trabajo en paralelo (predeterminado 3)",
                    "tr_TR": "Paralel çalışan işlem sayısı (varsayılan 3)",
                    "zh_CN": "并行工作进程数量（默认3）",
                    "ru_RU": "Количество параллельных рабочих процессов (по умолчанию 3)",
                    "pl_PL": "Liczba równoległych procesów roboczych (domyślnie 3)",
                    "uk_UA": "Кількість паралельних робочих процесів (за замовчуванням 3)",
                    "ja_JP": "並列ワーカープロセスの数（デフォルト3）",
                    "ko_KR": "병렬 작업자 프로세스 수 (기본값 3)",
                    "hi_IN": "समानांतर कार्यकर्ता प्रक्रियाओं की संख्या (डिफ़ॉल्ट 3)",
                    "bn_BD": "সমান্তরাল ওয়ার্কার প্রসেসের সংখ্যা (ডিফল্ট 3)",
                    "it_IT": "Numero di processi lavoratori paralleli (predefinito 3)",
                    "fr_FR": "Nombre de processus de travail parallèles (par défaut 3)",
                    "de_DE": "Anzahl der parallelen Arbeitsprozesse (Standard 3)",
                    "pt_PT": "Número de processos de trabalho paralelos (padrão 3)",
                    "ar_SA": "عدد عمليات العمل المتوازية (الافتراضي 3)",
                    "vi_VN": "Số lượng quy trình công việc song song (mặc định 3)",
                    "fa_IR": "تعداد فرآیندهای کارگر موازی (پیش‌فرض 3)",
                    "id_ID": "Jumlah proses pekerja paralel (default 3)",
                    "ms_MY": "Bilangan proses pekerja selari (lalai 3)",
                    "th_TH": "จำนวนกระบวนการทำงานแบบขนาน (ค่าเริ่มต้น 3)",
                    "ur_PK": "متوازی ورکر پروسیسز کی تعداد (ڈیفالٹ 3)",
                },
                "argument": "--parallelism",
                "range": [1, 16],
                "default": 3,
            },
        },
    },
}

AUTOMATIC_SAVE_MAP = {
    "save_next_to_input_subtitle": {
        "en_US": "Save next to input subtitle",
        "es_ES": "Guardar junto al subtítulo de entrada",
        "tr_TR": "Girdi altyazının yanına kaydet",
        "zh_CN": "保存在输入字幕旁边",
        "ru_RU": "Сохранить рядом с входными субтитрами",
        "pl_PL": "Zapisz obok wejściowego napisu",
        "uk_UA": "Зберегти поруч з вхідними субтитрами",
        "ja_JP": "入力字幕の隣に保存",
        "ko_KR": "입력 자막 옆에 저장",
        "hi_IN": "इनपुट उपशीर्षक के बगल में सहेजें",
        "bn_BD": "ইনপুট সাবটাইটেলের পাশে সংরক্ষণ করুন",
        "it_IT": "Salva accanto al sottotitolo di input",
        "fr_FR": "Enregistrer à côté du sous-titre d'entrée",
        "de_DE": "Neben Eingabeuntertitel speichern",
        "pt_PT": "Guardar junto à legenda de entrada",
        "ar_SA": "حفظ بجانب الترجمة المدخلة",
        "vi_VN": "Lưu bên cạnh phụ đề đầu vào",
        "fa_IR": "ذخیره در کنار زیرنویس ورودی",
        "id_ID": "Simpan di sebelah subtitle masukan",
        "ms_MY": "Simpan bersebelahan dengan sarikata input",
        "th_TH": "บันทึกถัดจากคำบรรยายนำเข้า",
        "ur_PK": "ان پٹ سب ٹائٹل کے ساتھ محفوظ کریں",
    },
    "overwrite_input_subtitle": {
        "en_US": "Overwrite input subtitle",
        "es_ES": "Sobrescribir subtítulo de entrada",
        "tr_TR": "Girdi altyazının üzerine yaz",
        "zh_CN": "覆盖输入字幕",
        "ru_RU": "Перезаписать входные субтитры",
        "pl_PL": "Nadpisz wejściowy napis",
        "uk_UA": "Перезаписати вхідні субтитри",
        "ja_JP": "入力字幕を上書き",
        "ko_KR": "입력 자막 덮어쓰기",
        "hi_IN": "इनपुट उपशीर्षक को अधिलेखित करें",
        "bn_BD": "ইনপুট সাবটাইটেল ওভাররাইট করুন",
        "it_IT": "Sovrascrivi sottotitolo di input",
        "fr_FR": "Écraser le sous-titre d'entrée",
        "de_DE": "Eingabeuntertitel überschreiben",
        "pt_PT": "Sobrescrever legenda de entrada",
        "ar_SA": "استبدال الترجمة المدخلة",
        "vi_VN": "Ghi đè phụ đề đầu vào",
        "fa_IR": "بازنویسی زیرنویس ورودی",
        "id_ID": "Timpa subtitle masukan",
        "ms_MY": "Tulis ganti sarikata input",
        "th_TH": "เขียนทับคำบรรยายนำเข้า",
        "ur_PK": "ان پٹ سب ٹائٹل پر لکھیں",
    },
    "save_next_to_video": {
        "en_US": "Save next to video",
        "es_ES": "Guardar junto al video",
        "tr_TR": "Videonun yanına kaydet",
        "zh_CN": "保存在视频旁边",
        "ru_RU": "Сохранить рядом с видео",
        "pl_PL": "Zapisz obok wideo",
        "uk_UA": "Зберегти поруч з відео",
        "ja_JP": "ビデオの隣に保存",
        "ko_KR": "비디오 옆에 저장",
        "hi_IN": "वीडियो के बगल में सहेजें",
        "bn_BD": "ভিডিওর পাশে সংরক্ষণ করুন",
        "it_IT": "Salva accanto al video",
        "fr_FR": "Enregistrer à côté de la vidéo",
        "de_DE": "Neben Video speichern",
        "pt_PT": "Guardar junto ao vídeo",
        "ar_SA": "حفظ بجانب الفيديو",
        "vi_VN": "Lưu bên cạnh video",
        "fa_IR": "ذخیره در کنار ویدیو",
        "id_ID": "Simpan di sebelah video",
        "ms_MY": "Simpan bersebelahan dengan video",
        "th_TH": "บันทึกถัดจากวิดีโอ",
        "ur_PK": "ویڈیو کے ساتھ محفوظ کریں",
    },
    "save_next_to_video_with_same_filename": {
        "en_US": "Save next to video with same filename",
        "es_ES": "Guardar junto al video con el mismo nombre",
        "tr_TR": "Aynı dosya adıyla videonun yanına kaydet",
        "zh_CN": "使用相同文件名保存在视频旁边",
        "ru_RU": "Сохранить рядом с видео с тем же именем файла",
        "pl_PL": "Zapisz obok wideo z tą samą nazwą pliku",
        "uk_UA": "Зберегти поруч з відео з тим же іменем файлу",
        "ja_JP": "同じファイル名でビデオの隣に保存",
        "ko_KR": "같은 파일명으로 비디오 옆에 저장",
        "hi_IN": "वीडियो के बगल में समान फ़ाइल नाम के साथ सहेजें",
        "bn_BD": "একই ফাইল নাম দিয়ে ভিডিওর পাশে সংরক্ষণ করুন",
        "it_IT": "Salva accanto al video con lo stesso nome file",
        "fr_FR": "Enregistrer à côté de la vidéo avec le même nom de fichier",
        "de_DE": "Neben Video mit gleichem Dateinamen speichern",
        "pt_PT": "Guardar junto ao vídeo com o mesmo nome de ficheiro",
        "ar_SA": "حفظ بجانب الفيديو بنفس اسم الملف",
        "vi_VN": "Lưu bên cạnh video với cùng tên file",
        "fa_IR": "ذخیره در کنار ویدیو با همان نام فایل",
        "id_ID": "Simpan di sebelah video dengan nama file yang sama",
        "ms_MY": "Simpan bersebelahan dengan video dengan nama fail yang sama",
        "th_TH": "บันทึกถัดจากวิดีโอด้วยชื่อไฟล์เดียวกัน",
        "ur_PK": "ویڈیو کے ساتھ ایک ہی فائل نام کے ساتھ محفوظ کریں",
    },
    "save_to_desktop": {
        "en_US": "Save to desktop",
        "es_ES": "Guardar en el escritorio",
        "tr_TR": "Masaüstüne kaydet",
        "zh_CN": "保存到桌面",
        "ru_RU": "Сохранить на рабочий стол",
        "pl_PL": "Zapisz na pulpicie",
        "uk_UA": "Зберегти на робочий стіл",
        "ja_JP": "デスクトップに保存",
        "ko_KR": "바탕 화면에 저장",
        "hi_IN": "डेस्कटॉप पर सहेजें",
        "bn_BD": "ডেস্কটপে সংরক্ষণ করুন",
        "it_IT": "Salva sul desktop",
        "fr_FR": "Enregistrer sur le bureau",
        "de_DE": "Auf dem Desktop speichern",
        "pt_PT": "Guardar no ambiente de trabalho",
        "ar_SA": "حفظ على سطح المكتب",
        "vi_VN": "Lưu vào màn hình chính",
        "fa_IR": "ذخیره در دسکتاپ",
        "id_ID": "Simpan ke desktop",
        "ms_MY": "Simpan ke desktop",
        "th_TH": "บันทึกไปที่เดสก์ท็อป",
        "ur_PK": "ڈیسک ٹاپ پر محفوظ کریں",
    },
    "select_destination_folder": {
        "en_US": "Select destination folder",
        "es_ES": "Seleccionar carpeta de destino",
        "tr_TR": "Hedef klasörü seç",
        "zh_CN": "选择目标文件夹",
        "ru_RU": "Выбрать папку назначения",
        "pl_PL": "Wybierz folder docelowy",
        "uk_UA": "Вибрати папку призначення",
        "ja_JP": "保存先フォルダを選択",
        "ko_KR": "대상 폴더 선택",
        "hi_IN": "गंतव्य फ़ोल्डर चुनें",
        "bn_BD": "গন্তব্য ফোল্ডার নির্বাচন করুন",
        "it_IT": "Seleziona cartella di destinazione",
        "fr_FR": "Sélectionner le dossier de destination",
        "de_DE": "Zielordner auswählen",
        "pt_PT": "Selecionar pasta de destino",
        "ar_SA": "اختر مجلد الوجهة",
        "vi_VN": "Chọn thư mục đích",
        "fa_IR": "انتخاب پوشه مقصد",
        "id_ID": "Pilih folder tujuan",
        "ms_MY": "Pilih folder destinasi",
        "th_TH": "เลือกโฟลเดอร์ปลายทาง",
        "ur_PK": "منزل فولڈر منتخب کریں",
    },
}

MANUAL_SAVE_MAP = {
    "save_next_to_input_subtitle": {
        "en_US": "Save next to input subtitle",
        "es_ES": "Guardar junto al subtítulo de entrada",
        "tr_TR": "Girdi altyazının yanına kaydet",
        "zh_CN": "保存在输入字幕旁边",
        "ru_RU": "Сохранить рядом с входными субтитрами",
        "pl_PL": "Zapisz obok wejściowego napisu",
        "uk_UA": "Зберегти поруч з вхідними субтитрами",
        "ja_JP": "入力字幕の隣に保存",
        "ko_KR": "입력 자막 옆에 저장",
        "hi_IN": "इनपुट उपशीर्षक के बगल में सहेजें",
        "bn_BD": "ইনপুট সাবটাইটেলের পাশে সংরক্ষণ করুন",
        "it_IT": "Salva accanto al sottotitolo di input",
        "fr_FR": "Enregistrer à côté du sous-titre d'entrée",
        "de_DE": "Neben Eingabeuntertitel speichern",
        "pt_PT": "Guardar junto à legenda de entrada",
        "ar_SA": "حفظ بجانب الترجمة المدخلة",
        "vi_VN": "Lưu bên cạnh phụ đề đầu vào",
        "fa_IR": "ذخیره در کنار زیرنویس ورودی",
        "id_ID": "Simpan di sebelah subtitle masukan",
        "ms_MY": "Simpan bersebelahan dengan sarikata input",
        "th_TH": "บันทึกถัดจากคำบรรยายนำเข้า",
        "ur_PK": "ان پٹ سب ٹائٹل کے ساتھ محفوظ کریں",
    },
    "overwrite_input_subtitle": {
        "en_US": "Overwrite input subtitle",
        "es_ES": "Sobrescribir subtítulo de entrada",
        "tr_TR": "Girdi altyazının üzerine yaz",
        "zh_CN": "覆盖输入字幕",
        "ru_RU": "Перезаписать входные субтитры",
        "pl_PL": "Nadpisz wejściowy napis",
        "uk_UA": "Перезаписати вхідні субтитри",
        "ja_JP": "入力字幕を上書き",
        "ko_KR": "입력 자막 덮어쓰기",
        "hi_IN": "इनपुट उपशीर्षक को अधिलेखित करें",
        "bn_BD": "ইনপুট সাবটাইটেল ওভাররাইট করুন",
        "it_IT": "Sovrascrivi sottotitolo di input",
        "fr_FR": "Écraser le sous-titre d'entrée",
        "de_DE": "Eingabeuntertitel überschreiben",
        "pt_PT": "Sobrescrever legenda de entrada",
        "ar_SA": "استبدال الترجمة المدخلة",
        "vi_VN": "Ghi đè phụ đề đầu vào",
        "fa_IR": "بازنویسی زیرنویس ورودی",
        "id_ID": "Timpa subtitle masukan",
        "ms_MY": "Tulis ganti sarikata input",
        "th_TH": "เขียนทับคำบรรยายนำเข้า",
        "ur_PK": "ان پٹ سب ٹائٹل پر لکھیں",
    },
    "save_to_desktop": {
        "en_US": "Save to desktop",
        "es_ES": "Guardar en el escritorio",
        "tr_TR": "Masaüstüne kaydet",
        "zh_CN": "保存到桌面",
        "ru_RU": "Сохранить на рабочий стол",
        "pl_PL": "Zapisz na pulpicie",
        "uk_UA": "Зберегти на робочий стіл",
        "ja_JP": "デスクトップに保存",
        "ko_KR": "바탕 화면에 저장",
        "hi_IN": "डेस्कटॉप पर सहेजें",
        "bn_BD": "ডেস্কটপে সংরক্ষণ করুন",
        "it_IT": "Salva sul desktop",
        "fr_FR": "Enregistrer sur le bureau",
        "de_DE": "Auf dem Desktop speichern",
        "pt_PT": "Guardar no ambiente de trabalho",
        "ar_SA": "حفظ على سطح المكتب",
        "vi_VN": "Lưu vào màn hình chính",
        "fa_IR": "ذخیره در دسکتاپ",
        "id_ID": "Simpan ke desktop",
        "ms_MY": "Simpan ke desktop",
        "th_TH": "บันทึกไปที่เดสก์ท็อป",
        "ur_PK": "ڈیسک ٹاپ پر محفوظ کریں",
    },
    "select_destination_folder": {
        "en_US": "Select destination folder",
        "es_ES": "Seleccionar carpeta de destino",
        "tr_TR": "Hedef klasörü seç",
        "zh_CN": "选择目标文件夹",
        "ru_RU": "Выбрать папку назначения",
        "pl_PL": "Wybierz folder docelowy",
        "uk_UA": "Вибрати папку призначення",
        "ja_JP": "保存先フォルダを選択",
        "ko_KR": "대상 폴더 선택",
        "hi_IN": "गंतव्य फ़ोल्डर चुनें",
        "bn_BD": "গন্তব্য ফোল্ডার নির্বাচন করুন",
        "it_IT": "Seleziona cartella di destinazione",
        "fr_FR": "Sélectionner le dossier de destination",
        "de_DE": "Zielordner auswählen",
        "pt_PT": "Selecionar pasta de destino",
        "ar_SA": "اختر مجلد الوجهة",
        "vi_VN": "Chọn thư mục đích",
        "fa_IR": "انتخاب پوشه مقصد",
        "id_ID": "Pilih folder tujuan",
        "ms_MY": "Pilih folder destinasi",
        "th_TH": "เลือกโฟลเดอร์ปลายทาง",
        "ur_PK": "منزل فولڈر منتخب کریں",
    },
}

COLORS = {
    "GREY": "#808080",
    "BLUE": "#6ab0de",
    "GREEN": "#42ad4a",
    "RED": "#c0392b",
    "ORANGE": "#e67e22",
    "GREY_BACKGROUND": "rgba(128, 128, 128, 0.15)",
    "GREY_BACKGROUND_HOVER": "rgba(128, 128, 128, 0.3)",
    "BLUE_BACKGROUND": "rgba(0, 102, 255, 0.05)",
    "BLUE_BACKGROUND_HOVER": "rgba(0, 102, 255, 0.1)",
    "GREEN_BACKGROUND": "rgba(66, 173, 73, 0.1)",
    "GREEN_BACKGROUND_HOVER": "rgba(66, 173, 73, 0.15)",
    "RED_BACKGROUND": "rgba(232, 78, 60, 0.1)",
    "RED_BACKGROUND_HOVER": "rgba(232, 78, 60, 0.15)",
    # Smart Deduplication - processed items styling
    "PROCESSED_BACKGROUND": "rgba(128, 128, 128, 0.25)",
    "PROCESSED_BACKGROUND_HOVER": "rgba(128, 128, 128, 0.35)",
    # Theme palette colors
    "DARK_BG": "#202326",
    "DARK_BASE": "#141618",
    "DARK_ALT": "#2c2f31",
    "DARK_BUTTON": "#292c30",
    "DARK_DISABLED": "#535353",
    "LIGHT_BG": "#eff0f1",
    "LIGHT_DISABLED": "#9a9999",
}

SUBTITLE_EXTENSIONS = [
    ".srt",
    ".vtt",
    ".sbv",
    ".sub",
    ".ass",
    ".ssa",
    ".dfxp",
    ".ttml",
    ".itt",
    ".stl",
    ".idx",
    ".smi",
]

VIDEO_EXTENSIONS = [
    ".mp4",
    ".mkv",
    ".avi",
    ".webm",
    ".flv",
    ".mov",
    ".wmv",
    ".mpg",
    ".mpeg",
    ".m4v",
    ".3gp",
    ".h264",
    ".h265",
    ".hevc",
]

EXTRACTABLE_SUBTITLE_EXTENSIONS = {
    "subrip": "srt",
    "ass": "ass",
    "webvtt": "vtt",
    "mov_text": "srt",
}

# Convert translation dictionaries to TranslationDict objects
translation_dicts = ["PROGRAM_TAGLINE", "PROGRAM_DESCRIPTION"]
for name in translation_dicts:
    if name in globals() and isinstance(globals()[name], dict):
        globals()[name] = TranslationDict(globals()[name])

# Convert save location dictionaries
for key in AUTOMATIC_SAVE_MAP:
    if isinstance(AUTOMATIC_SAVE_MAP[key], dict):
        AUTOMATIC_SAVE_MAP[key] = TranslationDict(AUTOMATIC_SAVE_MAP[key])

for key in MANUAL_SAVE_MAP:
    if isinstance(MANUAL_SAVE_MAP[key], dict):
        MANUAL_SAVE_MAP[key] = TranslationDict(MANUAL_SAVE_MAP[key])

# Convert SYNC_TOOLS descriptions and options to TranslationDict objects
for tool_name, tool_data in SYNC_TOOLS.items():
    if isinstance(tool_data.get("description"), dict):
        tool_data["description"] = TranslationDict(tool_data["description"])

    # Convert options labels and tooltips
    if "options" in tool_data:
        for option_name, option_data in tool_data["options"].items():
            if isinstance(option_data.get("label"), dict):
                option_data["label"] = TranslationDict(option_data["label"])
            if isinstance(option_data.get("tooltip"), dict):
                option_data["tooltip"] = TranslationDict(option_data["tooltip"])

            # Convert value_labels if present
            if "value_labels" in option_data:
                for value, label in option_data["value_labels"].items():
                    if isinstance(label, dict):
                        option_data["value_labels"][value] = TranslationDict(label)

# Set proper default language after LANGUAGES is defined
try:
    from utils import get_locale

    DEFAULT_OPTIONS["language"] = get_locale()
except ImportError:
    # Fallback to en_US if circular import occurs during initialization
    DEFAULT_OPTIONS["language"] = "en_US"
except Exception:
    # Fallback to en_US if any other error occurs during initialization
    DEFAULT_OPTIONS["language"] = "en_US"
